# Generated by Django 3.1.7 on 2021-03-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_messages_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='messages',
            new_name='message',
        ),
    ]
